// Code generated by dagger-compiler.  Do not edit.
package com.github.pedrovgs.sample.activity;


import dagger.MembersInjector;
import dagger.internal.Binding;
import dagger.internal.Linker;
import java.util.Set;
import javax.inject.Provider;

/**
 * A {@code Binder<PlacesSampleActivity>} implementation which satisfies
 * Dagger's infrastructure requirements including:
 *
 * Owning the dependency links between {@code PlacesSampleActivity} and its
 * dependencies.
 *
 * Being a {@code Provider<PlacesSampleActivity>} and handling creation and
 * preparation of object instances.
 *
 * Being a {@code MembersInjector<PlacesSampleActivity>} and handling injection
 * of annotated fields.
 */
public final class PlacesSampleActivity$$InjectAdapter extends Binding<PlacesSampleActivity>
    implements Provider<PlacesSampleActivity>, MembersInjector<PlacesSampleActivity> {
  private Binding<com.pedrogomez.renderers.RendererAdapter<com.github.pedrovgs.sample.viewmodel.PlaceViewModel>> placesAdapter;
  private Binding<DIFragmentActivity> supertype;

  public PlacesSampleActivity$$InjectAdapter() {
    super("com.github.pedrovgs.sample.activity.PlacesSampleActivity", "members/com.github.pedrovgs.sample.activity.PlacesSampleActivity", NOT_SINGLETON, PlacesSampleActivity.class);
  }

  /**
   * Used internally to link bindings/providers together at run time
   * according to their dependency graph.
   */
  @Override
  @SuppressWarnings("unchecked")
  public void attach(Linker linker) {
    placesAdapter = (Binding<com.pedrogomez.renderers.RendererAdapter<com.github.pedrovgs.sample.viewmodel.PlaceViewModel>>) linker.requestBinding("com.pedrogomez.renderers.RendererAdapter<com.github.pedrovgs.sample.viewmodel.PlaceViewModel>", PlacesSampleActivity.class, getClass().getClassLoader());
    supertype = (Binding<DIFragmentActivity>) linker.requestBinding("members/com.github.pedrovgs.sample.activity.DIFragmentActivity", PlacesSampleActivity.class, getClass().getClassLoader(), false, true);
  }

  /**
   * Used internally obtain dependency information, such as for cyclical
   * graph detection.
   */
  @Override
  public void getDependencies(Set<Binding<?>> getBindings, Set<Binding<?>> injectMembersBindings) {
    injectMembersBindings.add(placesAdapter);
    injectMembersBindings.add(supertype);
  }

  /**
   * Returns the fully provisioned instance satisfying the contract for
   * {@code Provider<PlacesSampleActivity>}.
   */
  @Override
  public PlacesSampleActivity get() {
    PlacesSampleActivity result = new PlacesSampleActivity();
    injectMembers(result);
    return result;
  }

  /**
   * Injects any {@code @Inject} annotated fields in the given instance,
   * satisfying the contract for {@code Provider<PlacesSampleActivity>}.
   */
  @Override
  public void injectMembers(PlacesSampleActivity object) {
    object.placesAdapter = placesAdapter.get();
    supertype.injectMembers(object);
  }
}
