// Code generated by dagger-compiler.  Do not edit.
package com.github.pedrovgs.sample.viewmodel;


import dagger.internal.Binding;
import javax.inject.Provider;

/**
 * A {@code Binder<PlaceCollectionViewModel>} implementation which satisfies
 * Dagger's infrastructure requirements including:
 *
 * Being a {@code Provider<PlaceCollectionViewModel>} and handling creation and
 * preparation of object instances.
 */
public final class PlaceCollectionViewModel$$InjectAdapter extends Binding<PlaceCollectionViewModel>
    implements Provider<PlaceCollectionViewModel> {

  public PlaceCollectionViewModel$$InjectAdapter() {
    super("com.github.pedrovgs.sample.viewmodel.PlaceCollectionViewModel", "members/com.github.pedrovgs.sample.viewmodel.PlaceCollectionViewModel", NOT_SINGLETON, PlaceCollectionViewModel.class);
  }

  /**
   * Returns the fully provisioned instance satisfying the contract for
   * {@code Provider<PlaceCollectionViewModel>}.
   */
  @Override
  public PlaceCollectionViewModel get() {
    PlaceCollectionViewModel result = new PlaceCollectionViewModel();
    return result;
  }
}
